name: Deploy Next.js ECS

on:
  push:
    branches: [ main ]

    workflow_dispatch:   #

jobs:
  deploy:
    runs-on: [self-hosted, ecs, prod]

    steps:
      - uses: actions/checkout@v4

      - name: Build & Restart
        run: |
          cd /webroot/next-app
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart nextjs-app
